/**
 * Knowledge Graph Node representation
 */
export interface GraphNode {
  id: string;
  name: string;
  type: string;
  filePath: string;
  metadata?: Record<string, unknown>;
}

/**
 * Knowledge Graph Edge relationship
 */
export interface GraphEdge {
  source: string;
  target: string;
  relationship: string;
}

/**
 * Repository Knowledge Graph
 */
export interface KnowledgeGraph {
  nodes: GraphNode[];
  edges: GraphEdge[];
}

/**
 * Execution Task for a single business/technical capability module
 */
export interface ModuleTask {
  id: string;
  moduleName: string;
  description: string;
  relatedNodes: string[];
  relatedFiles: string[];
  estimatedComplexity: 'low' | 'medium' | 'high';
  priority: number;
  dependencies: string[];
}

/**
 * Graph Provider Interface
 */
export interface GraphProvider {
  indexRepository?(repoPath: string): Promise<void>;
  getKnowledgeGraph(repoPath: string): Promise<KnowledgeGraph>;
}

/**
 * Planned execution tasks generated by Planner
 */
export interface ExecutionPlan {
  repoPath: string;
  tasks: ModuleTask[];
  createdAt: string;
}

/**
 * User Review Handler Interface
 */
export interface UserReviewHandler {
  reviewPlan(plan: ExecutionPlan): Promise<boolean>;
}

/**
 * Generated documentation bundle for one module
 */
export interface ModuleDocOutput {
  moduleName: string;
  technicalContent: string;
  businessContent: string;
}

/**
 * .okf/metadata.json structure
 */
export interface OKFMetadata {
  version: string;
  generatedAt: string;
  repoPath: string;
  modules: string[];
}
