import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { VidyaExporter, VidyaExporterOptions } from './index.js';
import { loadVidyaPackage } from './loader.js';

export class DocusaurusExporter implements VidyaExporter {
  async export(options: VidyaExporterOptions): Promise<void> {
    const targetDir = options.vidyaDir || (options as any).okfDir || '.';
    const { outputDir, title = 'Vidya End-to-End Documentation' } = options;
    const pkg = await loadVidyaPackage(targetDir);

    const docsDir = path.join(outputDir, 'docs');
    const docsTechDir = path.join(docsDir, 'technical');
    const docsBizDir = path.join(docsDir, 'business');

    await fs.mkdir(docsTechDir, { recursive: true });
    await fs.mkdir(docsBizDir, { recursive: true });

    // 1. Write E2E Master Flow doc if available
    if (pkg.e2eFlowContent) {
      await fs.writeFile(path.join(docsDir, 'e2e-flow.md'), pkg.e2eFlowContent, 'utf-8');
    }

    // 2. Write technical docs
    for (const [filename, content] of pkg.technicalDocs.entries()) {
      await fs.writeFile(path.join(docsTechDir, filename), content, 'utf-8');
    }

    // 3. Write business docs
    for (const [filename, content] of pkg.businessDocs.entries()) {
      await fs.writeFile(path.join(docsBizDir, filename), content, 'utf-8');
    }

    // 4. Write sidebars.ts
    const sidebarItems: string[] = [];

    if (pkg.e2eFlowContent) {
      sidebarItems.push(`    'e2e-flow'`);
    }

    if (pkg.technicalDocs.size > 0) {
      sidebarItems.push(`    {
      type: 'category',
      label: 'Technical Documentation',
      items: [
${Array.from(pkg.technicalDocs.keys())
  .map((f) => `        'technical/${f.replace(/\.md$/, '')}'`)
  .join(',\n')}
      ],
    }`);
    }

    if (pkg.businessDocs.size > 0) {
      sidebarItems.push(`    {
      type: 'category',
      label: 'Business Flow (Draft)',
      items: [
${Array.from(pkg.businessDocs.keys())
  .map((f) => `        'business/${f.replace(/\.md$/, '')}'`)
  .join(',\n')}
      ],
    }`);
    }

    const sidebarsContent = `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
${sidebarItems.join(',\n')}
  ],
};

export default sidebars;
`;
    await fs.writeFile(path.join(outputDir, 'sidebars.ts'), sidebarsContent, 'utf-8');

    // Write docusaurus.config.ts template
    const configContent = `import {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: '${title}',
  tagline: 'Generated by Vidya (Knowledge Graph & Flow Engine)',
  favicon: 'img/favicon.ico',
  url: 'https://localhost',
  baseUrl: '/',
  onBrokenLinks: 'ignore',
  onBrokenMarkdownLinks: 'warn',
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],
};

export default config;
`;
    await fs.writeFile(path.join(outputDir, 'docusaurus.config.ts'), configContent, 'utf-8');

    // Write package.json for Docusaurus site
    const docusaurusPkg = {
      name: title.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '0.0.0',
      private: true,
      scripts: {
        docusaurus: 'docusaurus',
        start: 'docusaurus start',
        build: 'docusaurus build',
        serve: 'docusaurus serve'
      },
      dependencies: {
        '@docusaurus/core': '^3.0.0',
        '@docusaurus/preset-classic': '^3.0.0',
        'react': '^18.0.0',
        'react-dom': '^18.0.0'
      }
    };
    await fs.writeFile(path.join(outputDir, 'package.json'), JSON.stringify(docusaurusPkg, null, 2), 'utf-8');
  }
}
