import * as fs from 'node:fs/promises';
import * as path from 'node:path';
import { OKFExporter, OKFExporterOptions } from './index.js';
import { loadOKFPackage } from './loader.js';

export class DocusaurusExporter implements OKFExporter {
  async export(options: OKFExporterOptions): Promise<void> {
    const { okfDir, outputDir, title = 'OKF Documentation' } = options;
    const pkg = await loadOKFPackage(okfDir);

    const docsTechDir = path.join(outputDir, 'docs', 'technical');
    const docsBizDir = path.join(outputDir, 'docs', 'business');

    await fs.mkdir(docsTechDir, { recursive: true });
    await fs.mkdir(docsBizDir, { recursive: true });

    // Write technical docs
    for (const [filename, content] of pkg.technicalDocs.entries()) {
      await fs.writeFile(path.join(docsTechDir, filename), content, 'utf-8');
    }

    // Write business docs
    for (const [filename, content] of pkg.businessDocs.entries()) {
      await fs.writeFile(path.join(docsBizDir, filename), content, 'utf-8');
    }

    // Write sidebars.ts
    const sidebarsContent = `import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Technical Documentation',
      items: [
${Array.from(pkg.technicalDocs.keys())
  .map((f) => `        'technical/${f.replace(/\.md$/, '')}'`)
  .join(',\n')}
      ],
    },
    {
      type: 'category',
      label: 'Business Flow (Draft)',
      items: [
${Array.from(pkg.businessDocs.keys())
  .map((f) => `        'business/${f.replace(/\.md$/, '')}'`)
  .join(',\n')}
      ],
    },
  ],
};

export default sidebars;
`;
    await fs.writeFile(path.join(outputDir, 'sidebars.ts'), sidebarsContent, 'utf-8');

    // Write docusaurus.config.ts template
    const configContent = `import {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

const config: Config = {
  title: '${title}',
  tagline: 'Generated by OKF (Open Knowledge Format)',
  favicon: 'img/favicon.ico',
  url: 'https://localhost',
  baseUrl: '/',
  onBrokenLinks: 'ignore',
  onBrokenMarkdownLinks: 'warn',
  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          routeBasePath: '/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],
};

export default config;
`;
    await fs.writeFile(path.join(outputDir, 'docusaurus.config.ts'), configContent, 'utf-8');

    // Write package.json for Docusaurus site
    const docusaurusPkg = {
      name: title.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '0.0.0',
      private: true,
      scripts: {
        docusaurus: 'docusaurus',
        start: 'docusaurus start',
        build: 'docusaurus build',
        serve: 'docusaurus serve'
      },
      dependencies: {
        '@docusaurus/core': '^3.0.0',
        '@docusaurus/preset-classic': '^3.0.0',
        'react': '^18.0.0',
        'react-dom': '^18.0.0'
      }
    };
    await fs.writeFile(path.join(outputDir, 'package.json'), JSON.stringify(docusaurusPkg, null, 2), 'utf-8');
  }
}
